# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Simsquad < Formula
  desc "Single-binary device-pool provisioner for parallel mobile QA."
  homepage "https://github.com/peuf0u/simsquad"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/peuf0u/simsquad/releases/download/v0.3.0/simsquad_0.3.0_darwin_amd64.tar.gz"
      sha256 "16aa3c10ac8749820b268ca1564c161db651127fff52d119b6c32cfd298cbc2f"

      define_method(:install) do
        bin.install "simsquad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/peuf0u/simsquad/releases/download/v0.3.0/simsquad_0.3.0_darwin_arm64.tar.gz"
      sha256 "92e98c6ee1a58f755c754ec46635c46bef1e8656b993a2d82da44e128d467ed3"

      define_method(:install) do
        bin.install "simsquad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/peuf0u/simsquad/releases/download/v0.3.0/simsquad_0.3.0_linux_amd64.tar.gz"
      sha256 "1265e855131068763cdd8e9892f9fa89714212082efff06af9608dcf4b4e9458"
      define_method(:install) do
        bin.install "simsquad"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peuf0u/simsquad/releases/download/v0.3.0/simsquad_0.3.0_linux_arm64.tar.gz"
      sha256 "8604ba35408d9c3f6d71d5ca6cc5c846b239b1e42d3e1688e99a2b13a2d0e555"
      define_method(:install) do
        bin.install "simsquad"
      end
    end
  end

  test do
    system "#{bin}/simsquad", "--version"
  end
end
